/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package invoicegenerator;

import java.util.List;

public class App {

    public static void main(String[] args) {
        InvoiceGenerator invoiceGenerator=new InvoiceGeneratorImpl();
        ExcelNameExtractor excelNameExtractor=new ExcelNameExtractorImpl();
        List<NameAmountPair> nameAmountPairs = excelNameExtractor.getNameAmountPairs("SampleDonaters.xlsx");
        for(NameAmountPair nameAmountPair: nameAmountPairs) {
            invoiceGenerator.generateInvoice(nameAmountPair.getName(),nameAmountPair.getAmount());
        }
    }
}
